---
vpc_name: "platform_homolog_vpc"
vpc_id: "vpc-051721395ecf1f7aa"
cluster_name: "eks-plugin-infracost"
cluster_version: "1.27"
cidr_block: 10.50.0.0/16
private_subnets:
  - 10.50.10.0/24
  - 10.50.20.0/24
  - 10.50.30.0/24
public_subnets:
  - 10.50.40.0/24
  - 10.50.50.0/24
  - 10.50.60.0/24
aws_availability_zones: ["us-east-1a","us-east-1b","us-east-1c"]
node_groups:
  eks-sample:
    desired_capacity: "3"
    max_capacity: "4"
    min_capacity: "1"
    ami_type: AL2_x86_64
    instance_types:
      - "m5.large"
    capacity_type: "ON_DEMAND"
cluster_enabled_log_types:
  - api
  - audit
  - authenticator
  - controllerManager
  - scheduler
users_list:
  - name: root-user
    role: root
tags:
  Project: VKPR
  Source: aws-eks
rolearn: "arn:aws:iam::559803878497:role/vault-admin-role"
